Lots of dgb_ -> od_ and dGB_ -> DTECT
git-svn-id: https://svn.opendtect.org/od/trunk@2861 a985855d-d384-4b45-ae33-31a410998c3c

diff --git a/bin/od_exec b/bin/od_exec
--- a/bin/od_exec
+++ b/bin/od_exec
@@ -2,19 +2,19 @@
 #_______________________________________________________________________________
 #
 # (C) 1999 de Groot-Bril Earth Sciences B.V.
-# $Id: od_exec,v 1.19 2003-06-13 14:15:36 arend Exp $
+# $Id: od_exec,v 1.20 2003-10-19 13:53:07 bert Exp $
 #
 # module startup script
 #_______________________________________________________________________________
 
-if ( ! $?dGB_APPL ) then
-	echo "Error : dGB program not initialized."
+if ( ! $?DTECT_APPL ) then
+	echo "$0 : Error : environment not initialized."
 	exit 1
 endif
 
-eval `$dGB_APPL/bin/mksethdir`
+eval `$DTECT_APPL/bin/mksethdir`
 
-set bindir="$dGB_APPL/bin/$binsubdir"
+set bindir="$DTECT_APPL/bin/$binsubdir"
 set nicecmd=""
 set extrascript=""
 set extraargs=""
@@ -47,8 +47,8 @@ else if ( "$1" == "--prescript" ) then
 
 	set extrascript="$2"
 	if ( ! -e $extrascript ) then
-	    if ( -e $dGB_APPL/bin/$extrascript ) then
-		set extrascript="$dGB_APPL/bin/$extrascript"
+	    if ( -e $DTECT_APPL/bin/$extrascript ) then
+		set extrascript="$DTECT_APPL/bin/$extrascript"
 	    else if ( -e $bindir/$extrascript ) then
 		set extrascript="$bindir/$extrascript"
 	    endif
@@ -64,7 +64,7 @@ else if ( "$1" == "--inxterm" || "$1" == "--inxterm+askclose" ) then
 	    set xtermcmdarg = "--askclose"
 	endif
 
-	set xtermcmd="xterm -bg lightyellow -fg black -geometry 80x25 -e $dGB_APPL/bin/dgb_xterm_exec $xtermcmdarg"
+	set xtermcmd="xterm -bg lightyellow -fg black -geometry 80x25 -e $DTECT_APPL/bin/od_xterm_exec $xtermcmdarg"
 
 	shift
 	goto next_arg
@@ -79,7 +79,7 @@ if ( ! -d $bindir ) then
 	exit 1
 endif
 
-setenv XAPPLRESDIR	$dGB_APPL/data
+setenv XAPPLRESDIR	$DTECT_APPL/data
 setenv PATH		"${bindir}:${PATH}"
 if ( $?LD_LIBRARY_PATH ) then
 	setenv LD_LIBRARY_PATH	"${bindir}/so:${LD_LIBRARY_PATH}"
@@ -95,10 +95,10 @@ endif
 
 
 if ( $issys == yes ) then
-	if ( $?dGB_DEBUG ) echo "$0 : $xtermcmd $nicecmd $* $extraargs"
+	if ( $?DTECT_DEBUG ) echo "$0 : $xtermcmd $nicecmd $* $extraargs"
 	$xtermcmd $nicecmd $* $extraargs
 else
-	if ( $?dGB_DEBUG ) echo "$0 : $xtermcmd $nicecmd $bindir/$* $extraargs"
+	if ( $?DTECT_DEBUG ) echo "$0 : $xtermcmd $nicecmd $bindir/$* $extraargs"
 	$xtermcmd $nicecmd $bindir/$* $extraargs
 endif
 
diff --git a/bin/od_exec_rmt b/bin/od_exec_rmt
--- a/bin/od_exec_rmt
+++ b/bin/od_exec_rmt
@@ -2,17 +2,17 @@
 #_______________________________________________________________________________
 #
 # (C) 1999,2002 de Groot-Bril Earth Sciences B.V.
-# $Id: od_exec_rmt,v 1.8 2003-04-28 08:22:04 arend Exp $
+# $Id: od_exec_rmt,v 1.9 2003-10-19 13:53:07 bert Exp $
 #
 # module remote startup script
 #_______________________________________________________________________________
 
-if ( $?dGB_DEBUG ) then
-    echo "$*" > /tmp/dgbdebug.log
+if ( $?DTECT_DEBUG ) then
+    echo "$*" > /tmp/oddebug.log
 endif
 
-if ( ! $?dGB_APPL ) then
-	echo "Error : dGB program not initialized."
+if ( ! $?DTECT_APPL ) then
+	echo "Error : environment not initialized."
 	exit 1
 endif
 
@@ -50,10 +50,10 @@ else if ( "$1" == "--transfervars" ) then
 	goto next_var
 endif
 
-set transf="setenv dGB_DATA $dGB_DATA +-+ setenv dGB_APPL $dGB_APPL"
+set transf="setenv DTECT_DATA $DTECT_DATA +-+ setenv DTECT_APPL $DTECT_APPL"
 
-if ( $?dGB_USER ) then
-	set transf="${transf} +-+ setenv dGB_USER $dGB_USER"
+if ( $?DTECT_USER ) then
+	set transf="${transf} +-+ setenv DTECT_USER $DTECT_USER"
 endif
 
 if ( $?LM_LICENSE_FILE ) then
@@ -84,9 +84,9 @@ end
 
 set transf="$transf +-+-+ $*"
 
-if ( $?dGB_DEBUG ) then
-    echo ${rshcomm} ${remotehost} ${dGB_APPL}/bin/dgb_do_rmt $transf >> /tmp/dgbdebug.log
+if ( $?DTECT_DEBUG ) then
+    echo ${rshcomm} ${remotehost} ${DTECT_APPL}/bin/od_do_rmt $transf >> /tmp/oddebug.log
 endif
 
-${rshcomm} ${remoteuser} ${remotehost} ${dGB_APPL}/bin/dgb_do_rmt $transf
+${rshcomm} ${remoteuser} ${remotehost} ${DTECT_APPL}/bin/od_do_rmt $transf
 exit 0
