Added automatic branch detection and error handling

diff --git a/dvs/arc_update b/dvs/arc_update
--- a/dvs/arc_update
+++ b/dvs/arc_update
@@ -1,13 +1,65 @@
 #!/bin/csh -f
 
-if ( $#argv > 0 ) then
-	set branchnm="$*"
+set curbranch=`git branch | /bin/grep '\*' | awk '{print $2}'`
+echo "Current branch: ${curbranch}"
+set mainbranch=`awk '{if($1=="\"arc.land.onto.default\":") print $2}' < ${WORK}/.arcconfig | sed 's/[",,]//g'`
+set brlist=`git branch -vv | /bin/grep -v origin | awk '{if($1=="*") print $2; else print $1}'`
+
+if ( $#brlist == 0 ) then
+    echo "$0: No local feature branches found"
+    exit
+else if ( $#brlist == 1 ) then
+    set branchnm=${brlist[1]}
 else
+    if ( $#argv > 0 ) then
+	set userinp="$*"
+    else
+	foreach brnm ( ${brlist} )
+	    if ( ${brnm} == ${curbranch} ) then
+		set branchnm=${brnm}
+		goto do_work
+	    endif
+	end
 	echo -n "Branch name: "
-	set branchnm="$<"
+	set userinp="$<"
+    endif
+    foreach brnm ( ${brlist} )
+	if ( ${brnm} == ${userinp} ) then
+	    set branchnm=${brnm}
+	endif
+    end
+    if ( ! $?branchnm ) then
+	echo "$0: ${userinp} is not a local feature branch"
+	exit 1
+    endif
 endif
 
-git checkout master
+do_work:
+
+echo "Going to update $branchnm"
+git checkout $mainbranch
+if ( $status != 0 ) then
+    echo "$0: Cannot checkout $mainbranch, fix errors and try again"
+    exit 1
+endif
+
 git pull --rebase
+if ( $status != 0 ) then
+    echo "$0: error while pulling $mainbranch, fix errors and try again"
+    exit 1
+endif
+
 git checkout "$branchnm"
-git rebase master
+if ( $status != 0 ) then
+    echo "$0: Cannot checkout $branchnm, fix errors and try again"
+    exit 1
+endif
+
+git rebase $mainbranch
+if ( $status != 0 ) then
+    echo "$0: Cannot rebase $branchnm with $mainbranch, fix errors and try again"
+    exit 1
+endif
+
+echo "Updated branch $branchnm successfully"
+exit 0
