Checking for .arcconfig

diff --git a/dvs/arc_push b/dvs/arc_push
--- a/dvs/arc_push
+++ b/dvs/arc_push
@@ -1,8 +1,21 @@
 #!/bin/csh -f
 
+if ( ! -e ./.arcconfig ) then
+    set gitroot=`git rev-parse --show-toplevel`
+    if ( ${gitroot} != ${PWD} ) then
+	echo "Changing directory to ${gitroot}"
+	cd ${gitroot}
+    endif
+endif
+
+if ( ! -e ./.arcconfig ) then
+    echo "${0}: Cannot find .arcconfig, "
+    exit 1
+endif
+
 set curbranch=`git branch | /bin/grep '\*' | awk '{print $2}'`
 echo "Current branch: ${curbranch}"
-set mainbranch=`awk '{if($1=="\"arc.land.onto.default\":") print $2}' < ${WORK}/.arcconfig | sed 's/[",,]//g'`
+set mainbranch=`awk '{if($1=="\"arc.land.onto.default\":") print $2}' < ./.arcconfig | sed 's/[",,]//g'`
 set brlist=`git branch -vv | /bin/grep -v origin | awk '{if($1=="*") print $2; else print $1}'`
 
 if ( $#brlist == 0 ) then
@@ -35,10 +48,28 @@ else
 endif
 
 do_work:
-echo "First running arc_update to bring $branchnm up-to-date with $mainbranch"
-arc_update $branchnm
+echo "First trying to bring $branchnm up-to-date with $mainbranch"
+git checkout $mainbranch
 if ( $status != 0 ) then
-    echo "${0}: error while updating $branchnm, fix errors and try again"
+    echo "${0}: Cannot checkout $mainbranch, fix errors and try again"
+    exit 1
+endif
+
+git pull --rebase
+if ( $status != 0 ) then
+    echo "${0}: error while pulling $mainbranch, fix errors and try again"
+    exit 1
+endif
+
+git checkout "$branchnm"
+if ( $status != 0 ) then
+    echo "${0}: Cannot checkout $branchnm, fix errors and try again"
+    exit 1
+endif
+
+git rebase $mainbranch
+if ( $status != 0 ) then
+    echo "${0}: Cannot rebase $branchnm with $mainbranch, fix errors and try again"
     exit 1
 endif
 
@@ -52,13 +83,7 @@ endif
 
 git checkout $mainbranch
 if ( $status != 0 ) then
-    echo "${0}- Cannot checkout $mainbranch, fix errors and try again"
-    exit 1
-endif
-
-git pull --rebase
-if ( $status != 0 ) then
-    echo "${0}: error while pulling $mainbranch, fix errors and try again"
+    echo "${0}: Cannot checkout $mainbranch, fix errors and try again"
     exit 1
 endif
 
diff --git a/dvs/arc_update b/dvs/arc_update
--- a/dvs/arc_update
+++ b/dvs/arc_update
@@ -1,8 +1,21 @@
 #!/bin/csh -f
 
+if ( ! -e ./.arcconfig ) then
+    set gitroot=`git rev-parse --show-toplevel`
+    if ( ${gitroot} != ${PWD} ) then
+	echo "Changing directory to ${gitroot}"
+	cd ${gitroot}
+    endif
+endif
+
+if ( ! -e ./.arcconfig ) then
+    echo "${0}: Cannot find .arcconfig, "
+    exit 1
+endif
+
 set curbranch=`git branch | /bin/grep '\*' | awk '{print $2}'`
 echo "Current branch: ${curbranch}"
-set mainbranch=`awk '{if($1=="\"arc.land.onto.default\":") print $2}' < ${WORK}/.arcconfig | sed 's/[",,]//g'`
+set mainbranch=`awk '{if($1=="\"arc.land.onto.default\":") print $2}' < ./.arcconfig | sed 's/[",,]//g'`
 set brlist=`git branch -vv | /bin/grep -v origin | awk '{if($1=="*") print $2; else print $1}'`
 
 if ( $#brlist == 0 ) then
