update for anon cvs access
git-svn-id: https://svn.opendtect.org/od/trunk@11346 a985855d-d384-4b45-ae33-31a410998c3c

diff --git a/setup_cvstree b/setup_cvstree
--- a/setup_cvstree
+++ b/setup_cvstree
@@ -1,6 +1,6 @@
 #!/bin/csh
 # This script initialises a work dir after CVS checkout
-# $Id: setup_cvstree,v 1.9 2007-12-10 15:37:32 cvsbert Exp $
+# $Id: setup_cvstree,v 1.10 2008-02-18 07:59:42 cvsnanne Exp $
 
 if ( $#argv < 1 ) then
     set od_wdir=`pwd`
@@ -17,13 +17,7 @@ if ( ! -d "$od_wdir" ) then
 endif
 
 cd "$od_wdir"
-if ( ! $?DGB_CVS_DIR ) then
-    setenv DGB_CVS_DIR $od_wdir/dvs
-    if ( $?WORK ) then
-        if ( -e $WORK/dvs ) setenv DGB_CVS_DIR $WORK/dvs
-    endif
-endif
-$DGB_CVS_DIR/dvs update
+cvs update -d -P
 
 ln -s Pmake/RootMakefile Makefile
 
@@ -83,50 +77,91 @@ else if ( $binsubdir == sol32 ) then
     cp /usr/local/lib/libstdc++.so.6 .
 endif
 
+set qtdir=
+set coindir=
+set fftwdir=
 set dosimvollib=0
-if ( ! -e /users/appman/bin/set_basedir.csh ) then
-    echo "make sure coin, qt and fftw .so libs are"
+if ( -e /users/appman/bin/set_basedir.csh ) then
+    set qtdir=$basedir/qt/devel
+    set coindir=$basedir/coin/devel
+    set fftwdir=$basedir/fftw/devel
+endif
+if ( $?OD_QTDIR ) then
+    set qtdir=$OD_QTDIR
+endif
+if ( $?OD_COINDIR ) then
+    set coindir=$OD_COINDIR
+endif
+if ( $?OD_FFTWDIR ) then
+    set fftwdir=$OD_FFTWDIR
+endif
+
+set missingpkgnms=
+if ( $qtdir == "" ) set missingpkgnms="Qt"
+if ( $coindir == "" ) set missingpkgnms="$missingpkgnms Coin"
+if ( $fftwdir == "" ) set missingpkgnms="$missingpkgnms FFTW"
+
+if ( $missingpkgnms != "" ) then
+    echo "Make sure $missingpkgnms .so libs are"
     echo "copied or linked to $od_wdir/bin/$binsubdir/so"
     echo "See the end $0 for details on what needs to be linked"
-else if ( $binsubdir == mac ) then
-    source /users/appman/bin/set_basedir.csh
-    ln -s $basedir/qt/rel/lib/libQt3Support.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtCore.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtGui.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtNetwork.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtOpenGL.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtSql.4.dylib .
-    ln -s $basedir/qt/rel/lib/libQtXml.4.dylib .
-    ln -s $basedir/coin/lib/libCoin.40.dylib .
-    ln -s $basedir/coin/lib/libSoQt.20.dylib .
-    ln -s $basedir/coin/lib/libsimage.20.dylib .
-    ln -s libsimage.20.dylib libsimage.dylib
-    ln -s $basedir/fftw/lib/libfftw3f.3.dylib .
-    ln -s libfftw3f.3.dylib libfftw3f.dylib
-    set dosimvollib=1
+endif
+if ( $binsubdir == mac ) then
+    if ( $qtdir != "" ) then
+	ln -s $qtdir/lib/libQt3Support.4.dylib .
+	ln -s $qtdir/lib/libQtCore.4.dylib .
+	ln -s $qtdir/lib/libQtGui.4.dylib .
+	ln -s $qtdir/lib/libQtNetwork.4.dylib .
+	ln -s $qtdir/lib/libQtOpenGL.4.dylib .
+	ln -s $qtdir/lib/libQtSql.4.dylib .
+	ln -s $qtdir/lib/libQtXml.4.dylib .
+    endif
+    if ( $coindir != "" ) then
+	ln -s $coindir/lib/libCoin.40.dylib .
+	ln -s $coindir/lib/libSoQt.20.dylib .
+	ln -s $coindir/lib/libsimage.20.dylib .
+	ln -s libsimage.20.dylib libsimage.dylib
+	set dosimvollib=1
+    endif
+    if ( $fftwdir != "" ) then
+	ln -s $fftwdir/lib/libfftw3f.3.dylib .
+	ln -s libfftw3f.3.dylib libfftw3f.dylib
+    endif
 else
-    source /users/appman/bin/set_basedir.csh
-    ln -s $basedir/qt/rel/lib/libQt3Support.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtCore.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtGui.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtNetwork.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtOpenGL.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtSql.so.4 .
-    ln -s $basedir/qt/rel/lib/libQtXml.so.4 .
-    ln -s $basedir/coin/lib/libCoin.so.40 .
-    ln -s $basedir/coin/lib/libSoQt.so.20 .
-    ln -s $basedir/coin/lib/libsimage.so.20 .
-    ln -s libsimage.so.20 libsimage.so
-    ln -s $basedir/fftw/lib/libfftw3f.so.3 .
-    ln -s libfftw3f.so.3 libfftw3f.so
-    set dosimvollib=1
+    if ( $qtdir != "" ) then
+	ln -s $qtdir/lib/libQt3Support.so.4 .
+	ln -s $qtdir/lib/libQtCore.so.4 .
+	ln -s $qtdir/lib/libQtGui.so.4 .
+	ln -s $qtdir/lib/libQtNetwork.so.4 .
+	ln -s $qtdir/lib/libQtOpenGL.so.4 .
+	ln -s $qtdir/lib/libQtSql.so.4 .
+	ln -s $qtdir/lib/libQtXml.so.4 .
+    endif
+    if ( $coindir != "" ) then
+	ln -s $coindir/lib/libCoin.so.40 .
+	ln -s $coindir/lib/libSoQt.so.20 .
+	ln -s $coindir/lib/libsimage.so.20 .
+	ln -s libsimage.so.20 libsimage.so
+	set dosimvollib=1
+    endif
+    if ( $fftwdir != "" ) then
+	ln -s $fftwdir/lib/libfftw3f.so.3 .
+	ln -s libfftw3f.so.3 libfftw3f.so
+    endif
 endif
 
 if ( $dosimvollib == 1 ) then
     cd "$od_wdir/lib/$binsubdir"
-    ln -s $basedir/coin/lib/libSimVoleon.a .
+    ln -s $coindir/lib/libSimVoleon.a .
     cd G
     ln -s ../libSimVoleon.a . >& /dev/null
     cd ../O
     ln -s ../libSimVoleon.a . >& /dev/null
 endif
+
+cd $od_wdir
+foreach fil ( init.bash init.csh )
+    sed -e "s%__WORK__%$od_wdir%" \
+	-e "s%__DTECTAPPL__DIR__%$od_wdir%" \
+	"$od_wdir/dtect/dtectspec/.$fil" > $fil
+end
