Displaying message to the user if dependent system libraries are missing.
Summary:
checking dependent libraries for Qt platforms/libqxcb.so library.
Displaying message to the user if libraryies not found.

Test Plan: tested on local and release machine. Message displayed  if system library not found.

Reviewers: arnaud

Reviewed By: arnaud

Subscribers: raman, lloyd, wayne

Differential Revision: https://phabricator.dgbes.com:8443/D13453

diff --git a/data/install_files/unixscripts/run_installer b/data/install_files/unixscripts/run_installer
--- a/data/install_files/unixscripts/run_installer
+++ b/data/install_files/unixscripts/run_installer
@@ -33,5 +33,19 @@ else
     fi
 fi
 
+qtfile=${curdir}/platforms/libqxcb.so
+if [ ! -f "$qtfile" ]; then
+    echo "Qt platform plugin file $qtfile not found."
+    echo "Can not display the installer window  without this file."
+    exit 1
+fi
+
+infomsg=`ldd $qtfile | grep "not found"`
+if [ "$infomsg" != "" ]; then
+    echo  "System libraries listed below are missing, please install them and rerun the installer"
+    echo "$infomsg"
+    exit 1
+fi
+
 "${curdir}/od_instmgr" "$@"
 exit $?
