Fixed incorrect message when launching the installer
The checks for missing system libraries were broken as a result of
the fix for Jira OD-2985.
Restored them.

diff --git a/data/install_files/unixscripts/run_installer b/data/install_files/unixscripts/run_installer
--- a/data/install_files/unixscripts/run_installer
+++ b/data/install_files/unixscripts/run_installer
@@ -145,12 +145,10 @@ fi
 
 infomsg=`ldd $qtfile | grep "not found"`
 if [[ -n "$infomsg" ]]; then
-    infomsg=`ldd $qtfile | grep "not found" | grep -v $pngfilenm`
-    if [[ -n "$infomsg" ]]; then
-	echo  "System libraries listed below are missing, please install them and rerun the installer"
-	echo "$infomsg"
-        exit 1
-    fi
+    echo "System libraries listed below are missing:"
+    echo "$infomsg"
+    echo "Please install them and rerun the installer"
+    exit 1
 fi
 
 #get rid of the OD environment.
